### PR TITLE
Last version

### PR DESCRIPTION
**Pull request by simoneg90**
Added the Pi0 stream - cff file in the python folder, DummyRecHit in the plugin folder with the Exception procedure when a recHit subDetId is >1.
Added the LoneBunch trigger - only in the HighPileUp cfg file (possible to use it or not - option='lonBunch') 
Added infoTree in the Analyzer before the cut to do studies of chi2 and energy cuts dependence

### CODE REVIEW

**Comment by previsualconsent** [comment]
It seems like this commit
"last version update" https://github.com/simoneg90/EcalTiming/commit/0a70102fe137b2dc35f31b849729b0d5eb753a20

has a lot of the changes that I made. Which makes this merge really confusing

**Comment by emanueledimarco** [comment]
where is the problem? Does it conflict when merging?

**Comment by previsualconsent** [comment]
it makes the history very messy, but I am working on merging it.
If you want to update your code, then a git pull should be done, so the
history makes sense.

**Comment by previsualconsent** [comment]
there will always be some conflicts with merging, the problem is not
combining our code more periodically, so there is quite a bit of divering

**Comment by simoneg90** [comment]
Of course this commit simoneg90@0a70102 has a lot of your changes...we agreed to use the same code and to unify the analysis, so you passed me your version and I copied it in mine
The only differences are the one listed in the pull request comments (just a typo...the option is 'loneBunch' not 'lonBunch'). We can scan the code together this afternoon (your morning) to see the differences and decide what to merge.

**Comment by previsualconsent** [comment]
I know, the point of using git though, is to simplify that process. I think
I was able to do most of the merge yesterday. I'm busy this afternoon but
I'll finish it before monday.

**Comment by shervin86** [comment]
Superseeded by PR #9

**Pull request closed without merging**
